### ISSUE TITLE
System can't seem to find sqlshare-pythonclient

### ISSUE THREAD

**Issue by jldimond** [uwescience/sqlshare-pythonclient#22]
Hi,
I can't seem to get sqlshare-pythonclient to work. I have it installed and the config file setup but when I try to run it in terminal or iPython it cannot be found. Someone who's been trying to help me thought the problem could stem from the fact that Linux has Python built-in, but I also have Anaconda installed. This is what I get when I type `$which python`: `/home/jay/anaconda/bin/python`

Could the system be looking for sqlshare-pythonclient there instead of where I currently have it at `/home/jay/sqlshare-pythonclient`?

**Comment by dhalperi** [comment]
Hi jay, can you copy the exact command you're running plus the output? And also ls in your directory?



—

**Comment by jldimond** [comment]
Hi Dan,

Here's what's in my directory:

jay@jay-UL30A:~$ ls
anaconda                        Eagle             R
Anaconda-2.1.0-Linux-x86_64.sh  examples.desktop  smartgit
Desktop                         Music             sql
Documents                       paper             sqlshare-pythonclient
Downloads                       Pictures          Templates
draft-saved.txt                 Public            Videos

And here's how I try to open it up in iPython:
![untitled2](https://cloud.githubusercontent.com/assets/9869457/6281958/cd3bc184-b880-11e4-8db3-d64f2fd690b0.png)

**Comment by kubu4** [comment]
Hey @dhalperi, I don't know if it helps, but the install log on @jldimond's SQLShare install showed the Python location of ```/usr/bin/python```, but (as he pointed out above), his system is using the ``/home/jay/anaconda/bin/python```. Not sure if this contributes to his issue, but I thought I'd throw it out there.

**Comment by dhalperi** [comment]
@kubu4  -- that seems right. I don't know or use Anaconda, but if Anaconda has its own version of `python` you will need to ensure that you install the sqlshare libraries using Anaconda's copy, not the systems's copy.

**Comment by jldimond** [comment]
Thanks Dan and Sam--I'll try this tonight or tomorrow and let you know if it works out.
